### ISSUE TITLE
Option to build without XRT

### ISSUE THREAD

**Issue by vkomenda** [Blaok/fpga-runtime#1]
It might be possible to build FRT without having XRT installed. For example, for producing cores to be used in the Vivado flow.

A crude approximation is https://github.com/vkomenda/fpga-runtime/commit/c97beaf3bd1999e7b2103ee898eb0384af5324f7.

The resulting FRT library is missing required symbols however:
```
$ g++ -o vadd -O2 vadd.cpp vadd-host.cpp -ltapa -lfrt -lglog -lgflags -lOpenCL
/usr/bin/ld: warning: libboost_context.so.1.65.1, needed by /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libtapa.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libtapa.so: undefined reference to `ontop_fcontext'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libtapa.so: undefined reference to `jump_fcontext'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libfrt.so: undefined reference to `fpga::internal::XilinxOpenclDevice::New(std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > > const&)'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libtapa.so: undefined reference to `make_fcontext'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib/libfrt.so: undefined reference to `fpga::internal::XilinxOpenclDevice::GetEnviron[abi:cxx11]()'
collect2: error: ld returned 1 exit status
```

**Comment by Blaok** [comment]
Building FRT without XRT does not seem to make any sense. The built FRT library does not depend on XRT directly; it only depends on OpenCL, so you should be able to install and use FRT without XRT, as long as you have a compatible OpenCL. Both the default OpenCL and CUDA's OpenCL should work. Do you have a specific reason to build FRT without XRT, other than the packaging issue that you reported in https://github.com/Blaok/tapa/issues/6?
