### ISSUE TITLE
Querying constrained devices crashes

### ISSUE THREAD

**Issue by jskimko** [Blaok/fpga-runtime#4]
If using constrained devices via cgroups, which can prevent users from accessing certain physical devices, the call to query available devices on the system via `clGetDeviceInfo` will crash prematurely in `xilinx_opencl_device.cpp:100` due to a strict `CL_CHECK` guard.

Suppose there are 4 FPGA devices on a machine and the user has access to only the 4th. Expected behavior would be that `frt` attempts to query each device in sequence (failing) until it reaches the 4th device, which it will return successfully. Given the call site logic in `src/frt/devices/opencl_device.cpp:165`, the following patch was tested and should be sufficient to address this issue:

```
diff --git a/src/frt/devices/xilinx_opencl_device.cpp b/src/frt/devices/xilinx_opencl_device.cpp
index 4edc1ec..6a0b7d6 100644
--- a/src/frt/devices/xilinx_opencl_device.cpp
+++ b/src/frt/devices/xilinx_opencl_device.cpp
@@ -97,8 +97,8 @@ class DeviceMatcher : public OpenclDeviceMatcher {
     const std::string device_name = device.getInfo<CL_DEVICE_NAME>();
     char bdf[32];
     size_t bdf_size = 0;
-    CL_CHECK(clGetDeviceInfo(device.get(), CL_DEVICE_PCIE_BDF, sizeof(bdf), bdf,
-                             &bdf_size));
+    cl_int rc = clGetDeviceInfo(device.get(), CL_DEVICE_PCIE_BDF, sizeof(bdf), bdf, &bdf_size);
+    if (rc != CL_SUCCESS) { return ""; }
     const std::string device_name_and_bdf =
         Concat({device_name, " (bdf=", bdf, ")"});
     LOG(INFO) << "Found device: " << device_name_and_bdf;
```

Is there any chance this patch could be applied? Our use case only involves Xilinx devices, but this should be applicable to other devices as well.

**Comment by Blaok** [comment]
PR is very welcome :) I can also try to apply the patch if you prefer that.
